[package]
name = "git-watcher"
version = "0.1.0"
edition = "2021"

[dependencies]
notify-rust = "4"
ansi-to-tui = "7.0.0"
crossterm = "0.27.0"
ratatui = { version = "0.29.0", features = ["crossterm"] }
regex = "1"